FROM alpine:3.7

ENV REFRESHED_AT=2017-11-28

RUN apk add --update \
  erlang=20.1.7-r2 \
  elixir=1.5.2-r0 \
  erlang-crypto \
  erlang-parsetools \
  erlang-syntax-tools \
  erlang-runtime-tools \
  git \
  make
